/************************Dashing devang kartik surya**********************/
/***********************c++ founder bejrne stroustrpf***********************/



#include<iostream.h>
#include<conio.h>
int main()
{
int x,y;
clrscr();
cout<<"Enter the first number";
cin>>x;
cout<<"Enter the second number";
cin>>y;
cout<<"Results is ="<<x+y<<endl;
cout<<"Results is ="<<x-y<<endl;
cout<<"results is ="<<x*y<<endl;
cout<<"Results is ="<<x/y<<endl;
getch();
}