 /*****************Dashing Devang kartik Suryavanshi***********************/
 /****************welcome to turbo c++ application***********************/


#include<stdio.h>
#include<conio.h>
int main()
{
char name[10];
float salary;
clrscr();
printf("Enter the good name : ");
scanf("%s",&name );
printf("Please Enter your salary : ");
scanf("%f",&salary);
printf("welcome Dashing %c and your salary %f Rs.",&name,&salary);
 getch();
}