/**************************DEVANG KARTIK************************************/

#include<stdio.h>
#include<conio.h>
int main()
{
int a,b;                  //find the gretest number
clrscr();
printf("Enter the first number" : );
scanf("%d",&a);
printf("Enter the second number" :);
scanf("%d",&b);
if(a>b)       //CONDITION
{
printf("%d is greater then %d",a);
}
else
{
printf("%d is greater then %d",b);
}
return 0;
}